---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: echo-express
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: NodePort
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


